# Generated by Django 4.0.4 on 2022-06-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_mod_number_mod_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod',
            name='number',
        ),
    ]
