# Generated by Django 4.0.4 on 2022-06-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_mod_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
