# Generated by Django 4.0.4 on 2022-06-29 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_mod_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod',
            name='name',
        ),
    ]
