# Generated by Django 4.1.2 on 2022-10-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_owner_id_alter_resto_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resto',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
