# Generated by Django 4.1.2 on 2022-10-31 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_resto_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resto',
            name='slug',
        ),
    ]
