# Generated by Django 4.1.2 on 2022-10-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_remove_resto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='resto',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
