# Generated by Django 4.1.2 on 2022-11-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_resto_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=250)),
                ('hotel', models.CharField(max_length=250)),
            ],
        ),
    ]
