# Generated by Django 4.1.2 on 2022-11-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
